<?php
return array (
  'content' => 
  array (
    'fieldid' => '136',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'content',
    'name' => '询盘内容',
    'tips' => '询盘内容不少于4个字符',
    'css' => '',
    'minlength' => '4',
    'maxlength' => '2000',
    'pattern' => '',
    'errortips' => '输入内容太长或太短！',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'100%\',
  \'height\' => \'250\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '250',
    'defaultvalue' => '',
    'enablehtml' => '1',
  ),
  'name' => 
  array (
    'fieldid' => '137',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'name',
    'name' => '联系人',
    'tips' => '姓名不短于2个字符',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请输入联系人姓名！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'phone' => 
  array (
    'fieldid' => '138',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'phone',
    'name' => '电话',
    'tips' => '电话号码不短于6个数字',
    'css' => '',
    'minlength' => '6',
    'maxlength' => '20',
    'pattern' => '/^[0-9-]{6,13}$/',
    'errortips' => '请输入正确的电话号码！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'email' => 
  array (
    'fieldid' => '139',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'email',
    'name' => '电子邮箱',
    'tips' => '请输入正确格式的邮箱',
    'css' => '',
    'minlength' => '5',
    'maxlength' => '0',
    'pattern' => '/^[\\w\\-\\.]+@[\\w\\-\\.]+(\\.\\w+)+$/',
    'errortips' => '请输入格式正确的邮箱地址！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'pro_model' => 
  array (
    'fieldid' => '171',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'pro_model',
    'name' => '产品CAS型号',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'未知\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '未知',
    'ispassword' => '0',
  ),
  'pro_name' => 
  array (
    'fieldid' => '170',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'pro_name',
    'name' => '产品名称',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
);
?>