<?php
return array (
  1 => 
  array (
    'posid' => '1',
    'modelid' => '12',
    'catid' => '0',
    'name' => '首页焦点图推荐',
    'maxnum' => '20',
    'extention' => 'price',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '12',
    'catid' => '12',
    'name' => '首页环保水处理图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '12',
    'catid' => '13',
    'name' => '首页日化洗涤图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '12',
    'catid' => '14',
    'name' => '首页电镀原料图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '12',
    'catid' => '16',
    'name' => '首页环保清洗图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '12',
    'catid' => '52',
    'name' => '首页表面活性剂图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '12',
    'catid' => '54',
    'name' => '首页消泡抑泡剂图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '12',
    'catid' => '49',
    'name' => '首页化学试剂图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '12',
    'catid' => '55',
    'name' => '首页防腐防霉图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '12',
    'catid' => '44',
    'name' => '首页特别推荐文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '12',
    'catid' => '55',
    'name' => '首页防腐防霉文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '1',
    'catid' => '0',
    'name' => '常见问题',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '12',
    'catid' => '49',
    'name' => '首页化学试剂文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '12',
    'catid' => '54',
    'name' => '首页消泡抑泡文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '12',
    'catid' => '12',
    'name' => '首页环保环保水处理文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '12',
    'catid' => '13',
    'name' => '首页日化洗涤文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '12',
    'catid' => '14',
    'name' => '首页电镀原料文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '12',
    'catid' => '16',
    'name' => '首页环保清洗文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '12',
    'catid' => '52',
    'name' => '首页表面活性剂文字推荐',
    'maxnum' => '40',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '1',
    'catid' => '6',
    'name' => '热点新闻',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  37 => 
  array (
    'posid' => '37',
    'modelid' => '12',
    'catid' => '44',
    'name' => '首页特别推荐图片推荐',
    'maxnum' => '6',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>