<?php
return array (
  54 => 
  array (
    'typeid' => '54',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱3级',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '3级分类',
  ),
  55 => 
  array (
    'typeid' => '55',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱3级2',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  56 => 
  array (
    'typeid' => '56',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漂洗3级1111',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  57 => 
  array (
    'typeid' => '57',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漂洗3级222222',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  58 => 
  array (
    'typeid' => '58',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漂洗3级333333',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  59 => 
  array (
    'typeid' => '59',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漂洗3级444444',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  60 => 
  array (
    'typeid' => '60',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漂洗3级555555',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  61 => 
  array (
    'typeid' => '61',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漂洗3级666666',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  62 => 
  array (
    'typeid' => '62',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漂洗3级777777',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  64 => 
  array (
    'typeid' => '64',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '环保水三级',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  65 => 
  array (
    'typeid' => '65',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱下1',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  66 => 
  array (
    'typeid' => '66',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱下2',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  67 => 
  array (
    'typeid' => '67',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱下3',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  68 => 
  array (
    'typeid' => '68',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱下4',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  69 => 
  array (
    'typeid' => '69',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱下5',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  70 => 
  array (
    'typeid' => '70',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱下6',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  71 => 
  array (
    'typeid' => '71',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '片碱下7',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
);
?>